### PR TITLE
add common stuff.

### PR DESCRIPTION
**Pull request by morvencao**

### CODE REVIEW

**Comment by gyliu513** [comment]
image

@morvencao Why those failed jobs do not have `Detail`?

**Comment by morvencao** [comment]
@gyliu513 linter issue, fixing it.

**Comment by gyliu513** [comment]
What is wrong here ? Why some same items?

image

**Comment by gyliu513** [comment]
@morvencao can we rename `lint` to `check`, and enable `check` includes `lint`, `vet` and `fmt`?

**Comment by morvencao** [comment]
@gyliu513 I don't know how it happens, maybe github issue.

**Comment by gyliu513** [comment]
/assign @xunpan 

Just for test.

**Comment by morvencao** [comment]
Finally, pass the linter, @gyliu513 can you help to add `/lgtm` label.

**Pull request merged**
